# -*- coding: utf-8 -*-
"""
@author: Jerry
"""

process_data = {
  "quotationproductInfos": [
    {
      "pcode": "AA0015",
      "pname": "Eukaryote mRNA-seq",
      "itemsubcatname": "US product lines",
      "cycle": "",
      "isforprocess": "N",
      "isurgent": "0",
      "kfquotationid": "",
      "currencynow": "USD",
      "samplenum": 6,
      "genenum": "0",
      "unit": "2",
      "datasize": 6,
      "dataunit": "4",
      "isstandard": "N",
      "isanalyze": "",
      "isflow": "", 
      "pricecalculation": "0"
    }
  ],
  "quoprocessInfos": [
    {
      "processname": "GAA0003",
      "processcode": "Sample QC",
      "processtype": "LAA0104",
      "processtypename": "RNA Sample QC",
      "samnum": 6,
      "genenum": "0",
      "unit": "2",
      "univalence": "15",
      "slimitupper": "infinit",
      "slimitlower": "0",
      "nlimitupper": "infinit",
      "nlimitlower": "0",
      "dlimitupper": "infinit",
      "dlimitlower": "0",
      "tlimitupper": "infinit",
      "tlimitlower": "0",
      "currency": "USD",
      "datasize": "——",
      "dataunit": "——",
      "kfquotationid": "",
      "pcode": "AA0015",
      "pname": "Eukaryote mRNA-seq",
      "serialnumber": 1,
      "reserveprice": "",
      "saleprice": "",
      "regionalprice": "",
      "directorprice": ""
    },
    {
      "processname": "GY0001",
      "processcode": "建库",
      "processtype": "LAA0038",
      "processtypename": "Regular mRNA library",
      "samnum": 6,
      "genenum": "0",
      "unit": "2",
      "univalence": "0.1",
      "slimitupper": "infinit",
      "slimitlower": "0",
      "nlimitupper": "infinit",
      "nlimitlower": "0",
      "dlimitupper": "infinit",
      "dlimitlower": "0",
      "tlimitupper": "infinit",
      "tlimitlower": "0",
      "currency": "USD",
      "datasize": "——",
      "dataunit": "——",
      "kfquotationid": "",
      "pcode": "AA0015",
      "pname": "Eukaryote mRNA-seq",
      "serialnumber": 2,
      "reserveprice": "",
      "saleprice": "",
      "regionalprice": "",
      "directorprice": ""
    },
    {
      "processname": "GY0002",
      "processcode": "上机（按数据量报价）",
      "processtype": "LAA0117",
      "processtypename": "Sequencing(PE150)",
      "samnum": 6,
      "genenum": "0",
      "unit": "2",
      "univalence": "0.1",
      "slimitupper": "infinit",
      "slimitlower": "0",
      "nlimitupper": "infinit",
      "nlimitlower": "0",
      "dlimitupper": "infinit",
      "dlimitlower": "0",
      "tlimitupper": "infinit",
      "tlimitlower": "0",
      "currency": "USD",
      "datasize": 6,
      "dataunit": "4",
      "kfquotationid": "",
      "pcode": "AA0015",
      "pname": "Eukaryote mRNA-seq",
      "serialnumber": 3,
      "reserveprice": "",
      "saleprice": "",
      "regionalprice": "",
      "directorprice": ""
    },
    {
      "processname": "GAA0017",
      "processcode": "Bioinformatics analysis with $199 Package (Promotion Option 1)",
      "processtype": "LAA0123",
      "processtypename": "Standard Analysis(Agricultural part－with reference)",
      "samnum": 6,
      "genenum": "0",
      "unit": "2",
      "univalence": "0.1",
      "slimitupper": "23",
      "slimitlower": "0",
      "nlimitupper": "infinit",
      "nlimitlower": "0",
      "dlimitupper": "infinit",
      "dlimitlower": "0",
      "tlimitupper": "infinit",
      "tlimitlower": "0",
      "currency": "USD",
      "datasize": "——",
      "dataunit": "——",
      "kfquotationid": "",
      "pcode": "AA0015",
      "pname": "Eukaryote mRNA-seq",
      "serialnumber": 4,
      "reserveprice": "",
      "saleprice": "",
      "regionalprice": "",
      "directorprice": ""
    },
    {
      "processname": "GAA0007",
      "processcode": "Data release",
      "processtype": "LAA0047",
      "processtypename": "FTP",
      "samnum": 6,
      "genenum": "0",
      "unit": "2",
      "univalence": "0.1",
      "slimitupper": "infinit",
      "slimitlower": "0",
      "nlimitupper": "infinit",
      "nlimitlower": "0",
      "dlimitupper": "infinit",
      "dlimitlower": "0",
      "tlimitupper": "infinit",
      "tlimitlower": "0",
      "currency": "USD",
      "datasize": "——",
      "dataunit": "——",
      "kfquotationid": "",
      "pcode": "AA0015",
      "pname": "Eukaryote mRNA-seq",
      "serialnumber": 5,
      "reserveprice": "",
      "saleprice": "",
      "regionalprice": "",
      "directorprice": ""
    }
  ]
}
process_dict_library = {
  "quotationproductInfos": [
    {
      "pcode": "AA0032",
      "pname": "Pre-made libraries Lane sequencing",
      "itemsubcatname": "US product lines",
      "cycle": "",
      "isforprocess": "Y",
      "isurgent": "0",
      "kfquotationid": "96845E61D01D4D16E053260811ACE9B0",
      "currencynow": "USD",
      "samplenum": 1,
      "genenum": "",
      "unit": "",
      "datasize": 1,
      "dataunit": "8",
      "isstandard": "N",
      "isanalyze": "",
      "isflow": "",
      "pricecalculation": "0"
    }
  ],
    "quoprocessInfos": [
      {
        "processname": "GAA0022",
        "processcode": "Library quality control",
        "processtype": "LAA0101",
        "processtypename": "Regular library QC (Qubit+Agilent2100+QPCR)",
        "samnum": 2,
        "genenum": "0",
        "unit": "2",
        "univalence": "15",
        "slimitupper": "infinit",
        "slimitlower": "0",
        "nlimitupper": "infinit",
        "nlimitlower": "0",
        "dlimitupper": "infinit",
        "dlimitlower": "0",
        "tlimitupper": "infinit",
        "tlimitlower": "0",
        "currency": "USD",
        "datasize": "——",
        "dataunit": "——",
        "kfquotationid": "96845E61D01D4D16E053260811ACE9B0",
        "pcode": "AA0032",
        "pname": "Pre-made libraries Lane sequencing",
        "serialnumber": 1,
        "reserveprice": "",
        "saleprice": "",
        "regionalprice": "",
        "directorprice": ""
    },
    {
        "processname": "GY0002",
        "processcode": "上机（按数据量报价）",
        "processtype": "LAA0052",
        "processtypename": "HiSeq PE150 (Lane sequencing)",
        "samnum": 1,
        "genenum": "0",
        "unit": "2",
        "univalence": "0.1",
        "slimitupper": "infinit",
        "slimitlower": "0",
        "nlimitupper": "infinit",
        "nlimitlower": "0",
        "dlimitupper": "infinit",
        "dlimitlower": "0",
        "tlimitupper": "infinit",
        "tlimitlower": "0",
        "currency": "USD",
        "datasize": 1,
        "dataunit": "8",
        "kfquotationid": "96845E61D01D4D16E053260811ACE9B0",
        "pcode": "AA0032",
        "pname": "Pre-made libraries Lane sequencing",
        "serialnumber": 2,
        "reserveprice": "",
        "saleprice": "",
        "regionalprice": "",
        "directorprice": ""
    },
    {
        "processname": "GY0005",
        "processcode": "分析（按样本量报价）",
        "processtype": "LAA0172",
        "processtypename": "Data QC",
        "samnum": 1,
        "genenum": "0",
        "unit": "2",
        "univalence": "0.1",
        "slimitupper": "infinit",
        "slimitlower": "0",
        "nlimitupper": "infinit",
        "nlimitlower": "0",
        "dlimitupper": "infinit",
        "dlimitlower": "0",
        "tlimitupper": "infinit",
        "tlimitlower": "0",
        "currency": "USD",
        "datasize": 1,
        "dataunit": "8",
        "kfquotationid": "96845E61D01D4D16E053260811ACE9B0",
        "pcode": "AA0032",
        "pname": "Pre-made libraries Lane sequencing",
        "serialnumber": 3,
        "reserveprice": "",
        "saleprice": "",
        "regionalprice": "",
        "directorprice": ""
    },
    {
        "processname": "GAA0007",
        "processcode": "Data release",
        "processtype": "LAA0047",
        "processtypename": "FTP",
        "samnum": 1,
        "genenum": "0",
        "unit": "2",
        "univalence": "0.1",
        "slimitupper": "infinit",
        "slimitlower": "0",
        "nlimitupper": "infinit",
        "nlimitlower": "0",
        "dlimitupper": "infinit",
        "dlimitlower": "0",
        "tlimitupper": "infinit",
        "tlimitlower": "0",
        "currency": "USD",
        "datasize": "——",
        "dataunit": "——",
        "kfquotationid": "96845E61D01D4D16E053260811ACE9B0",
        "pcode": "AA0032",
        "pname": "Pre-made libraries Lane sequencing",
        "serialnumber": 4,
        "reserveprice": "",
        "saleprice": "",
        "regionalprice": "",
        "directorprice": ""
    }
  ]
}

process_dict = {
  "eukmrnaseq": [
    "AA0015",
    ["GAA0003", "GY0001", "GY0002", "GAA0017", "GAA0007"],
    ["LAA0104", "LAA0038", "LAA0117", "LAA0123", "LAA0047"],
  ],
  "premade-novas4": [
    "AA0032",
    ["GAA0022", "GY0002", "GY0005", "GAA0007"],
    ["LAA0101", "LAA0087", "LAA0172", "LAA0047"],
  ],
  "premade-novasp": [
    "AA0032",
    ["GAA0022", "GY0002", "GY0005", "GAA0007"],
    ["LAA0101", "LAA0196", "LAA0172", "LAA0047"],
  ],
  "premade-hiseq": [
    "AA0032",
    ["GAA0022", "GY0002", "GY0005", "GAA0007"],
    ["LAA0101", "LAA0052", "LAA0172", "LAA0047"],
  ],
  "prokmrnaseq": [
    "AA0021",
    ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
    ["LAA0104", "LAA0098", "LAA0114", "LAA0123", "LAA0047"],
  ],
  "lncrnaseq": [
    "AA0017",
    ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
    ["LAA0104", "LAA0105", "LAA0114", "LAA0151", "LAA0047"],
  ],
  "hwgs": [
      "AA0004",
      ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
      ["LAA0025", "LAA0029", "LAA0114", "LAA0151", "LAA0047"],
  ],
  "hwes": [
      "AA0005",
      ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
      ["LAA0025", "LAA0075", "LAA0114", "LAA0151", "LAA0047"],
  ],
  "mwes": [
      "AA0028",
      ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
      ["LAA0025", "LAA0032", "LAA0114", "LAA0151", "LAA0047"],
  ],
  "pawgs": [
      "AA0012",
      ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
      ["LAA0025", "LAA0029", "LAA0114", "LAA0151", "LAA0047"],
  ],
  "microbialwgs": [
      "AA0009",
      ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
      ["LAA0025", "LAA0029", "LAA0114", "LAA0151", "LAA0047"],
  ],
  "metagenomics": [
      "AA0006",
      ["GAA0003", "GY0001", "GY0002", "GY0005", "GAA0007"],
      ["LAA0025", "LAA0029", "LAA0114", "LAA0151", "LAA0047"],
  ]
}

process_SIF_dict = {
  "kfappointmentInfo": {
    "batchid": "",
    "batchno": "",
    "contractid": "9C2C70421FC56D23E053260811ACE26D",
    "contractno": "H202SC20011281",
    "contractname": "Davis-US-UMICH-27-Human-EukmRNAseq-WOBI-NVUS2019121644-rev-010720",
    "desc21": "",
    "desc24": "",
    "banlancemoney": "",
    "customercontractname": "",
    "desc22": "CP2020011600002",
    "corpname": "University of Michigan",
    "customeremail": "",
    "projectnum": "X202SC20011281",
    "projectname": "Davis-US-UMICH-27-Human-EukmRNAseq-WOBI-NVUS2019121644-rev-010720",
    "salesquono": "",
    "corpcontact": "Jerry",
    "corpphone": "-",
    "corpemail": "jerry.jie@novogeneusa.com",
    "backupcorpcontact": "",
    "backupcorpphone": "",
    "backupcorpemail": "",
    "desc23": "jerry.jie",
    "salesname": "Ruili Jie",
    "salesphone": "",
    "salesemail": "jerry.jie@novogeneusa.com",
    "senddate": "",
    "wishtime": "",
    "desc10": "",
    "desc11": "",
    "desc12": "122703",
    "desc13": "04451B6C-4154-4343-83E2-43156684EFC1",
    "expresscompany": "FedEx",
    "expresnumber": "NSHIP201912164401",
    "transportationcond": "01",
    "desc14": "",
    "desc15": "",
    "desc16": "",
    "desc17": "",
    "desc18": "",
    "desc19": "",
    "desc20": "202",
    "sampletypearray": "",
    "samplecount": "",
    "desc7": "1",
    "desc8": "",
    "desc9": "01",
    "desc3": "",
    "desc4": "",
    "desc1": "",
    "desc2": "",
    "circulationtype": "1",
    "mixornot": "3",
    "mixexplain": "",
    "remark": "",
    "recordercode": "",
    "recorderdesc": "",
    "recordtime": "",
    "businesstype": "12",
    "status": "",
    "desc27": "N",
    "desc28": "",
    "disptatus": "",
    "auflag": "",
    "auditflag": "",
    "submitcorp": "024004",
    "corpcode": "",
    "corpdesc": "",
    "workflowid": "",
    "version": "",
    "iscreatedatainfo": "0"
  }
}