"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os


APP = ['graphic.py']
#DATA_FILES = ['support-section', '../QuoteTemplate/Templates']
DATA_FILES = ['support-section', ('', ['../QuoteTemplate/Templates'])]

OPTIONS = {
    'plist': {
        'CFBundleName': 'Quotegenerator',
        'CFBundleDisplayName': 'Quotegenerator',
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2018, Novogene, All Rights Reserved"
    },
    'frameworks' : [
        '/Users/yiwenzhang/miniconda3/envs/quotegenerator/lib/libffi.6.dylib',
        '/Users/yiwenzhang/miniconda3/envs/quotegenerator/lib/libtk8.6.dylib',
        '/Users/yiwenzhang/miniconda3/envs/quotegenerator/lib/libtcl8.6.dylib'
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
